namespace xSimAtc_Terminal_WinUI
{
    [Microsoft.UI.Xaml.Data.Bindable]
    runtimeclass ViewContainer
    {
        String Title{ get; };
        Object Content{ get; };
    }

    [Microsoft.UI.Xaml.Data.Bindable]
    [default_interface]
    runtimeclass MainViewModel :
        Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        MainViewModel();

        String Title{ get; };
        ViewContainer SelectedView{ get; };

        event Windows.Foundation.EventHandler<Object> NavigateToTowerRequested;
        event Windows.Foundation.EventHandler<Object> NavigateToTrackingsRequested;

        void NavigateToTower();
        void NavigateToTrackings();
        void SelectView(ViewContainer view);
    }
}
